### ISSUE TITLE
Productivity and performance?

### ISSUE THREAD

**Issue by pavelthq** [danielsz/mmailer#1]
Hello everyone.

Do you have any benchmarks for your script?

How it will work in huge databases? (500k Users) with 50k/hourly emails?
What minimal configuration is needed to send 1 000 000 emails / monthly? and 50 000 every 5 minutes? (10k/minute)

Thanks for work!

**Comment by danielsz** [comment]
The purpose of mmailer is to send bulk email via non-bulk email providers, so it is optimized to send email **slower** rather than faster. 
For high-volume, high-throughput email systems, I would probably look at commercial services like Mailgun or Mandrill.

**Comment by edudemy** [comment]
Hello @danielsz 
Could this be used with multiple gmail accounts to send bulk mail
 to overcome gmail restrictions of 500 per day.

**Comment by danielsz** [comment]
Not out of the box.

**Comment by edudemy** [comment]
Thanks. So its like the Mailmerge functionality, I'm running currently with a Google Apps script template. The bulk mailer in the description could be misinterpreted for actually large (read 1000s of mails)  newsletter.

**Comment by danielsz** [comment]
People are using it for 1000s of mails. The sending is spread out over days.
